### ISSUE TITLE
Auto start not working

### ISSUE THREAD

**Issue by supra89t** [ngandrass/freenas-spindown-timer#3]
Hello,

This script works great once I run it manually. However it will not auto start for me. I followed your guide and placed the file on the nas and setup the smart settings and task. rebooted and the drives stay spinning. If I run the command manually it will work and keep spinning the disks down after the time set.

FreeNAS-11.3-U3.1
No VM's or anything
OS installed on 2 240GB SSD's
Pool is 24 1TB HDD's in 3 vdevs of Raid-z2 (15tb usable space)

The dataset is set to freenas-boot

The system hardware is:

Dell R730xd
2x Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz
PERC H730 Min (in HBA mode)
384GB DDR4 1866Mhz ECC ram
24x 1TB 7200RPM HDD
2x 240GB SSD (for mirrored os)

**Comment by ngandrass** [comment]
Heyho supra89t,

can you please provide the following additional information?
1. Where have you placed the `spindown_timer.sh` script? Is this location accessible right after boot? Do you might need to use the delayed start script? See: https://github.com/ngandrass/freenas-spindown-timer#delayed-start-ie-script-placed-in-encrypted-pool
2. Is the scripts execution bit set? Which command do you use to start the script manually?
3. Please provide a screenshot of the configured "Init/Shutdown Script".

Apart from that you can check if the script is actually getting executed after boot. See: https://github.com/ngandrass/freenas-spindown-timer#verify-autostart

I hope that we can quickly fix your issue :)

**Comment by supra89t** [comment]
I placed it on the root of the boot drive, that did not work, placed it on a SSD pool, same issue. Both can be run manually though.

![Annotation 2020-06-06 144044](https://user-images.githubusercontent.com/25457950/83952015-d62f1700-a803-11ea-87bd-71d88be43903.png)
![Annotation 2020-06-06 144045](https://user-images.githubusercontent.com/25457950/83952016-d62f1700-a803-11ea-9ede-2ee69fd81a04.png)
![Annotation 2020-06-06 144046](https://user-images.githubusercontent.com/25457950/83952017-d6c7ad80-a803-11ea-9eb2-638eedadfede.png)

**Comment by ngandrass** [comment]
> I ran the chmod -x on the file, when I run it manually i run it as bash ./spindown_timer.sh

I think we found the problem: It's `chmod +x spindown_timer.sh` with a `+` not a `-`.

Using `-x` actually discards the executable flag, hereby leading to an unexecutable script (unless you explicitly run it via `bash`). You should be able to execute the script as `/mnt/SSD/Scripts/spindown_timer.sh` (note the missing `bash` in front).

Please try setting the executable bit correctly by `chmod +x /mnt/SSD/Scripts/spindown_timer.sh` and run the script trough either `/mnt/SSD/Scripts/spindown_timer.sh` or when in the Scripts-folder directly as `./spindown_timer.sh`.

**Comment by supra89t** [comment]
Thank you! you are right. Its working now, system is idle at 140W compared to 240W. Seeing as this will be a plex media server, newer movies will be kept in the cache and will not need to spin up the disks. And with 384GB of RAM @ 8Gb/Movie ... thats a lot of movies lol

**Comment by ngandrass** [comment]
I'm glad to hear that the script now works for you :)

If you experience problems in the future feel free to open another issue.
