### ISSUE TITLE
Not Working on TrueNAS Core 12.0

### ISSUE THREAD

**Issue by Frankie3142** [ngandrass/freenas-spindown-timer#6]
Hi
I installed the spin down script on my TrueNAS Core version 12.0, running one SATA HDD (and a boot USB). I set the timeout to 5 mins for testing purposes, and the io check to one minute.

I found regular announcements that the USB stick had been spun down successfully(!), but no mention of the hard drive (which indeed never did spin down). I set the Storage/Disc settings as per your instructions. Nothing seemed to work.
Plese note I am not a Linux expert by the way!

Is this not something that works under SATA? Could the problem lie elsewhere?

Thank you for your thoughts.

Frankie.

**Comment by ngandrass** [comment]
Hey Frankie,

could you please post the full command (including parameters) that you use to start the spindown script?

Please also provide the output of there two commands:

1. `iostat -x`
2. `geom disk list`

Thanks :)

**Comment by Frankie3142** [comment]
Hi Niels!
Thank you for your kind response. I have the information you requested (below) but first I should tell you two things I have since learnt (I am a real beginner with TrueNAS!) which I now think will frustrate your script and may be the cause of the HDD not stopping. 1. System disks cannot be spun down! ... I am experimenting and learning about TrueNAS using only 1 HDD disk at the moment (plus a boot USB disk), and so the system is on the HDD, hence it cannot spin down I think? Also, 2. plugins & their jails are also on the HDD - I have read that a disk with a plugin cannot spin down either - this is really bad news for me if it's true.

I was thinking of getting a small inexpensive SDD - say 125Gig - to use as a system disk, JUST so i can spin down the main disks when not in use. Would that be a good idea do you think? Is 125GIG enough space for the system and 3 or 4 plugins?

Anyway here is the info you asked for, just in case it's still helpful.

Parameters.
(I set these to work quickly so I could tell if anything was stopping)
# ##################################################

TIMEOUT=60       # Default timeout before considering a drive as idle
POLL_TIME=20      # Default time to wait during a single iostat call
IGNORED_DRIVES=""  # Default list of drives that are never spun down
MANUAL_MODE=0      # Default manual mode setting
QUIET = 0
VERBOSE = 0
DRYRUN = 0

# ##################################################

Also the iostat command:

                       extended device statistics
device       r/s     w/s     kr/s     kw/s  ms/r  ms/w  ms/o  ms/t qlen  %b
ada0           7       2   5727.3     48.6    13     0    91    10    0   4
da0            0       0      2.4      0.2     1     7     0     2    0   0
cd0            0       0      0.0      0.0     0     0     0     0    0   0
pass0          0       0      0.0      0.0    22     0    15    21    0   0
pass1          0       0      0.0      0.0     0     0     0     0    0   0
pass2          0       0      0.0      0.0     0     0     0     0    0   0
pass3          0       0      0.0      0.0     5     0     0     5    0   0


And lastly the geom command:

Geom name: cd0
Providers:
1. Name: cd0
   Mediasize: 0 (0B)
   Sectorsize: 2048
   Mode: r0w0e0
   descr: hp CDDVDW SH-216DB
   ident: (null)
   rotationrate: unknown
   fwsectors: 0
   fwheads: 0

Geom name: ada0
Providers:
1. Name: ada0
   Mediasize: 2000398934016 (1.8T)
   Sectorsize: 512
   Stripesize: 4096
   Stripeoffset: 0
   Mode: r2w2e5
   descr: ST2000DM001-1CH164
   lunid: 5000c50065f4341e
   ident: Z1E6YYSE
   rotationrate: 7200
   fwsectors: 63
   fwheads: 16

Geom name: da0
Providers:
1. Name: da0
   Mediasize: 30752636928 (29G)
   Sectorsize: 512
   Mode: r1w1e2
   descr: SanDisk Ultra USB 3.0
   lunname: SanDisk Ultra USB 3.0   4C530001320824121063
   lunid: SanDisk Ultra USB 3.0   4C530001320824121063
   ident: 4C530001320824121063
   rotationrate: unknown
   fwsectors: 63
   fwheads: 255

Thank you Neils!

Regards

Frankie Rockett.


________________________________

**Comment by Frankie3142** [comment]
Hi Niels!

[THIS IS A DUPLICATION AS I AM NOT SURE THE FIRST TIME SENT CORRECTLY!]

Thank you for your kind response. I have the information you requested (below) but first I should tell you two things I have since learnt (I am a real beginner with TrueNAS!) which I now think will frustrate your script and may be the cause of the HDD not stopping. 1. System disks cannot be spun down! ... I am experimenting and learning about TrueNAS using only 1 HDD disk at the moment (plus a boot USB disk), and so the system is on the HDD, hence it cannot spin down I think? Also, 2. plugins & their jails are also on the HDD - I have read that a disk with a plugin cannot spin down either - this is really bad news for me if it's true.

I was thinking of getting a small inexpensive SDD - say 125Gig - to use as a system disk, JUST so i can spin down the main disks when not in use. Would that be a good idea do you think? Is 125GIG enough space for the system and 3 or 4 plugins?

Anyway here is the info you asked for, just in case it's still helpful.

Parameters.
(I set these to work quickly so I could tell if anything was stopping)
# ##################################################

TIMEOUT=60       # Default timeout before considering a drive as idle
POLL_TIME=20      # Default time to wait during a single iostat call
IGNORED_DRIVES=""  # Default list of drives that are never spun down
MANUAL_MODE=0      # Default manual mode setting
QUIET = 0
VERBOSE = 0
DRYRUN = 0

# ##################################################

Also the iostat command:

                       extended device statistics
device       r/s     w/s     kr/s     kw/s  ms/r  ms/w  ms/o  ms/t qlen  %b
ada0           7       2   5727.3     48.6    13     0    91    10    0   4
da0            0       0      2.4      0.2     1     7     0     2    0   0
cd0            0       0      0.0      0.0     0     0     0     0    0   0
pass0          0       0      0.0      0.0    22     0    15    21    0   0
pass1          0       0      0.0      0.0     0     0     0     0    0   0
pass2          0       0      0.0      0.0     0     0     0     0    0   0
pass3          0       0      0.0      0.0     5     0     0     5    0   0


And lastly the geom command:

Geom name: cd0
Providers:
1. Name: cd0
   Mediasize: 0 (0B)
   Sectorsize: 2048
   Mode: r0w0e0
   descr: hp CDDVDW SH-216DB
   ident: (null)
   rotationrate: unknown
   fwsectors: 0
   fwheads: 0

Geom name: ada0
Providers:
1. Name: ada0
   Mediasize: 2000398934016 (1.8T)
   Sectorsize: 512
   Stripesize: 4096
   Stripeoffset: 0
   Mode: r2w2e5
   descr: ST2000DM001-1CH164
   lunid: 5000c50065f4341e
   ident: Z1E6YYSE
   rotationrate: 7200
   fwsectors: 63
   fwheads: 16

Geom name: da0
Providers:
1. Name: da0
   Mediasize: 30752636928 (29G)
   Sectorsize: 512
   Mode: r1w1e2
   descr: SanDisk Ultra USB 3.0
   lunname: SanDisk Ultra USB 3.0   4C530001320824121063
   lunid: SanDisk Ultra USB 3.0   4C530001320824121063
   ident: 4C530001320824121063
   rotationrate: unknown
   fwsectors: 63
   fwheads: 255

Thank you Neils!

Regards

Frankie Rockett.

**Comment by ngandrass** [comment]
Hey Fankie,

please excuse my very delayed response!

> and so the system is on the HDD, hence it cannot spin down I think?

This is indeed a problem. Your system dataset is frequently accessed and therefore wakes the disk from standby. Theoretically the HDD can be spun down but it is spun up by the system nearly immediately, effectively preventing spindown.

> Also, 2. plugins & their jails are also on the HDD - I have read that a disk with a plugin cannot spin down either

As with the system dataset, plugins/jails may produce disk I/O that spins up the HDD.

To sum it up: You can unfortunately only spin down disks that neither contain your system dataset nor any running jails/VMs.

> I was thinking of getting a small inexpensive SDD - say 125Gig - to use as a system disk, JUST so i can spin down the main disks when not in use. Would that be a good idea do you think? Is 125GIG enough space for the system and 3 or 4 plugins?

This is exactly what I was about to suggest :) Placing the system dataset and all jails/VMs on a separate SSD allows you to spin down your HDDs.

But there is a potential pitfall to keep in mind. All data that is frequently accessed by the plugins/jails wakes the drives it is stored on. The amount of "hot data" you have determines the required size of your SSD. All other "cold data" can be stored on the HDDs.

Kind regards
Niels
