### ISSUE TITLE
Does this come to SCALE as well?

### ISSUE THREAD

**Issue by derWalter** [ngandrass/freenas-spindown-timer#8]
I would love to have this script adopted for truenas SCALE,
could this be done easily?

**Comment by ngandrass** [comment]
_As a disclaimer: I neither worked with TrueNAS SCALE nor am I even remotely familiar with it._

The spindown script itself does not rely on TrueNAS functions. It is solely using tools from the underlying BSD system. Therefore, it should be compatible with TrueNAS SCALE as well, though the setup/deployment procedure may vary.

Feel free to perform a quick test and let us know how it went :) Thanks!

**Comment by derWalter** [comment]
atm it doesnt.

**Comment by ngandrass** [comment]
Hey folks, check out the latest release v2.0.1 - I successfully tested it today on TrueNAS SCALE :)

See: https://github.com/ngandrass/truenas-spindown-timer/releases/tag/v2.0.1
